In [1]:
import numpy as np
x_test = np.load('data/X_test.npz')['arr_0']
x_train = np.load('data/X_train.npz')['arr_0']
y_train = np.load('data/Y_train.npz')['arr_0']

In [2]:
y_train[:10]

array([[1.30754295e-01, 1.22285765e+02, 8.03669961e-01],
       [9.92038437e-01, 1.77303640e+02, 5.98635874e-01],
       [8.93321366e-01, 2.47923577e+02, 6.03514602e-01],
       [8.75883738e-01, 2.00437572e+02, 7.77381163e-01],
       [7.72367570e-01, 1.35865729e+02, 5.82696123e-01],
       [9.91782471e-01, 1.67985236e+02, 6.49121986e-01],
       [6.24681677e-01, 2.84464179e+01, 9.57199157e-01],
       [5.67137188e-01, 4.65857881e+01, 6.63695939e-01],
       [7.55718050e-01, 4.59157088e+01, 6.12601455e-01],
       [3.78410973e-01, 3.58039504e+01, 8.26610373e-01]])

In [3]:
print('x_test:',x_test.shape)
print('x_train:',x_train.shape)
print('y_train:',y_train.shape)

x_test: (2500, 10000)
x_train: (47500, 10000)
y_train: (47500, 3)


In [4]:
y_train[:,0].shape

(47500,)

# Linear Regression

In [4]:
from sklearn import linear_model
linear_reg = linear_model.LinearRegression()
linear_reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [5]:
import pickle
with open('model/linear_reg.pkl','wb') as model:
    pickle.dump(linear_reg,model)

In [6]:
y_pred_linear_reg = linear_reg.predict(x_test)

In [7]:
y_pred_linear_reg.shape

(2500, 3)

In [8]:
np.savetxt('pred_linear_reg.csv',y_pred_linear_reg,delimiter=',')

# Ridge Regression

In [9]:
from sklearn import linear_model
linear_ridge_reg = linear_model.Ridge(alpha=.5)
linear_ridge_reg.fit(x_train,y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [10]:
y_pred_ridge_reg = linear_ridge_reg.predict(x_test)

In [11]:
np.savetxt('pred_ridge_reg.csv',y_pred_ridge_reg,delimiter=',')

# Lasso

In [13]:
from sklearn import linear_model
#x_train /= x_train.std(axis=0)
Lasso_reg = linear_model.Lasso(alpha=0.1,max_iter=10000,tol=0.0001)
Lasso_reg.fit(x_train,y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=10000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [14]:
y_pred_Lasso_reg = Lasso_reg.predict(x_test)

In [15]:
np.savetxt('pred_Lasso_reg.csv',y_pred_Lasso_reg,delimiter=',')

# ElasticNet

In [18]:
from sklearn.linear_model import ElasticNet
Elastic_reg = ElasticNet(random_state=0)
Elastic_reg.fit(x_train,y_train)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [19]:
y_pred_Elastic_reg = Elastic_reg.predict(x_test)

In [20]:
np.savetxt('pred_Elastic_reg.csv',y_pred_Elastic_reg,delimiter=',')

# Least Angle Regression

In [21]:
from sklearn import linear_model
LAR_reg = linear_model.Lars()
LAR_reg.fit(x_train,y_train)

Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True,
   fit_path=True, n_nonzero_coefs=500, normalize=True, positive=False,
   precompute='auto', verbose=False)

In [22]:
y_pred_LAR_reg = LAR_reg.predict(x_test)

In [23]:
np.savetxt('pred_LAR_reg.csv',y_pred_LAR_reg,delimiter=',')

# XGBoost

In [ ]:
import xgboost as xgb
from sklearn.multioutput import MultiOutputRegressor
# xgdmat = xgb.DMatrix(x_train,y_train)
# params = {'objective':'mae'}
# final_gb = xgb.train(params,xgdmat)
multioutput_regressor = MultiOutputRegressor(xgb.XGBRegressor(objective='reg:linear')).fit(x_train,y_train)
y_pred_xgboost = multioutput_regressor.predict(x_test)

In [4]:
np.savetxt('pred_xgboost_reg.csv',y_pred_xgboost,delimiter=',')

# LightGBM

In [10]:
import lightgbm as lgb
from sklearn.externals import joblib
from sklearn.multioutput import MultiOutputRegressor
bst = MultiOutputRegressor(lgb.LGBMRegressor(objective='mape')).fit(x_train[:100],y_train[:100])
y_pred_lightgbm = bst.predict(x_test[:10])
np.savetxt('pred_lightgbm_reg.csv',y_pred_lightgbm,delimiter=',')
joblib.dump(bst, 'bst.pkl')

['bst.pkl']

In [11]:
load_model = joblib.load('bst.pkl')

In [12]:
print(load_model)

MultiOutputRegressor(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
       importance_type='split', learning_rate=0.1, max_depth=-1,
       min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
       n_estimators=100, n_jobs=-1, num_leaves=31, objective='mape',
       random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
       subsample=1.0, subsample_for_bin=200000, subsample_freq=0),
           n_jobs=None)


In [8]:
y_pred_lightgbm

array([[3.46838903e-01, 1.54689915e+02, 5.65919994e-01],
       [5.55811642e-01, 1.29335821e+02, 8.90814082e-01],
       [6.23188895e-01, 1.18893843e+02, 8.06928084e-01],
       [1.50032210e-01, 1.21101851e+02, 8.09364557e-01],
       [3.72077710e-01, 1.13312602e+02, 7.83787643e-01],
       [7.29344081e-01, 1.32551930e+02, 8.32653645e-01],
       [6.29160844e-01, 1.09369955e+02, 8.93586235e-01],
       [2.84316161e-01, 1.69228030e+02, 5.73141349e-01],
       [1.85005460e-01, 5.64537529e+01, 8.85357768e-01],
       [7.36757675e-01, 1.43074447e+02, 7.12977376e-01]])

# Adaboost

In [3]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.externals import joblib
ada_reg = MultiOutputRegressor(AdaBoostRegressor(base_estimator=DecisionTreeRegressor(max_depth=3), loss='square',n_estimators=100)).fit(x_train[:100],y_train[:100])
y_pred_adaboost_dt = ada_reg.predict(x_test[:10])

In [4]:
np.savetxt('pred_adaboost_dt_reg.csv',y_pred_adaboost_dt,delimiter=',')
joblib.dump(ada_reg, 'ada.pkl')

['ada.pkl']

In [5]:
y_pred_adaboost

array([[4.83694640e-01, 1.76544702e+02, 5.63101293e-01],
       [5.50491343e-01, 1.29154423e+02, 9.11015047e-01],
       [6.00817280e-01, 1.50489266e+02, 8.19984183e-01],
       [1.70893817e-01, 1.14992005e+02, 8.01018652e-01],
       [1.93893473e-01, 1.54995566e+02, 7.85020066e-01],
       [5.24372972e-01, 1.40469545e+02, 8.20600205e-01],
       [5.66955771e-01, 1.50489266e+02, 8.99425599e-01],
       [1.82261413e-01, 1.58239589e+02, 5.34278887e-01],
       [1.82261413e-01, 1.05151144e+02, 9.02835543e-01],
       [6.87122666e-01, 1.55996182e+02, 7.07264976e-01]])